-- ============================================================
-- seed.sql
-- ------------------------------------------------------------
-- No hay datos de dominio en el seed: profiles depende de auth.users reales.
-- Este archivo se conserva para que `supabase db reset` sea reproducible.
-- ============================================================
